  language: cpp

  group: stable

  dist: precise
  addons:
    apt:
      packages:
         - gcc
  before_install: 
            - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install gcc; fi
  script:
            g++ -std=c++11 ai.cpp -o ai
  os: 
     - osx
     - linux
