  language: cpp

  group: stable

  dist: precise
  before_install: 
            #- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then rvm reinstall ruby-head --binary; fi
            #- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install gcc; fi
            - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install clang; fi

  script:
            - clang++ -std=c++11 ai.cpp files.cpp -o ai
            - clang++ -std=c++11 test.cpp files.cpp -o test
            - ./test
  os: 
     - osx
     #- linux todo: fix later
